- obs space:
    name: icec___OBS_PLAT__
    distribution: *obs_distribution
    obsdatain:  {obsfile: __OBS_IN_FILE__}
    obsdataout: {obsfile: __OBS_OUT_DIR__/icec___OBS_PLAT__.nc}
    simulated variables: [sea_ice_area_fraction]
  obs operator:
    name: Identity
  obs error:
    covariance model: diagonal
  obs localization: # note, this is only used for LETKF
    localization method: Gaspari-Cohn
    lengthscale: 200e3
    search method: kd_tree
  obs filters:
  - *obs_land_mask
  - filter: Bounds Check
    minvalue: 0.0
    maxvalue: 1.0
  - filter: Background Check
    threshold: 5.0
  - filter: Domain Check
    where:
    - variable: { name: sea_surface_temperature@GeoVaLs}
      maxvalue: 0.9
