- obs space:
    name: icet___OBS_PLAT__
    distribution: *obs_distribution
    obsdatain:  {obsfile: __OBS_IN_FILE__}
    obsdataout: {obsfile: __OBS_OUT_DIR__/icet___OBS_PLAT__.nc}
    simulated variables: [sea_ice_category_thickness]
  obs operator:
    name: Identity
  obs error:
    covariance model: diagonal
  obs localization: # note, this is only used for LETKF
    localization method: Gaspari-Cohn
    lengthscale: 200e3
    search method: kd_tree
  obs filters:
  - *obs_land_mask
  - filter: Bounds Check
    minvalue: 0.0
    maxvalue: 10.0
  - filter: Background Check
    threshold: 500.0
  - filter: Domain Check
    where:
    - variable: { name: sea_ice_category_thickness@GeoVaLs}
      minvalue: 0.1
