- obs space:
    name: swh___OBS_PLAT__
    distribution: *obs_distribution
    obsdatain:  {obsfile: __OBS_IN_FILE__}
    obsdataout: {obsfile: __OBS_OUT_DIR__/swh___OBS_PLAT__.nc}
    simulated variables: [sea_surface_wave_significant_height]
  obs operator:
    name: Identity
  obs error:
    covariance model: diagonal
    obs localizations:
    - localization method: Horizontal Gaspari-Cohn
      lengthscale: 200e3
  obs filters:
  - *obs_land_mask
  - filter: Bounds Check
    minvalue: 0.0
    maxvalue: 18.0
  - filter: Domain Check
    where:
    - variable: {name: distance_from_coast@GeoVaLs}
      minvalue: 100e3 #50e3 #40000
  - filter: Background Check
    absolute threshold: 5.0
