geometry:
  mom6_input_nml: mom_input.nml
  fields metadata: fields_metadata.yaml

model:
  name: SOCA
  tstep: PT1H
  advance_mom6: 1
  model variables: [cicen, hicen, hsnon, socn, tocn, ssh, hocn]

initial condition:
  read_from_file: 1
  date: &date __FCST_START_TIME__
  basename: RESTART_IN/
  ocn_filename: MOM.res.nc
  ice_filename: cice.res.nc
  state variables: [cicen, hicen, hsnon, socn, tocn, ssh, hocn]

forecast length: __FCST_LEN__

output:
  frequency: PT48H
  datadir: Data
  exp: mom6soca
  date: *date
  type: fc
